POST http://localhost:5135/api/auth/register
Content-Type: application/json

{
  "username": "Mohamed_Shady",
  "password": "1234"
}

###
POST http://localhost:5135/api/auth/login
Content-Type: application/json

{
  "username": "Mohamed_Shady",
  "password": "1234"
}

